
---
- name: Add unit file for Puma
  template:
    src: puma.service.j2
    dest: /etc/systemd/system/puma.service
  notify: reload puma

- name: Add config for DB connection
  template:
    src: db_config.j2
    dest: /home/{{ app_user }}/db_config
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: enable puma
  systemd: name=puma enabled=yes
